### ISSUE TITLE
Alternative names to trigger listening/response?

### ISSUE THREAD

**Issue by dehuszar** [mysamai/mysam#12]
As someone who's name is Sam, it would be nice to switch the triggering name to something else.  Is this possible?  I did not see anything to this effect in the README.

**Comment by daffl** [comment]
Very good point. There currently is no trigger mechanism other than pressing `CTRL + Space` though. It won't listen until you press `CTRL + Space` and then only until the end of the sentence.

I initially had it listen continuously and we might bring it back (definitely with a customizable trigger) but there were a lot of false positives which made it much harder to train.
